<a href="https://colab.research.google.com/github/TABEYWICKRAMA/BigData/blob/main/NumPy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Import NumPy Library**


*   NumPy most usable feature is n dimentional array object, similar to python lists.




So why we use NumPy,


1.   Less memory
2.   Fast
3.   Convinient






----------------------------------------------------------------------------------

In [110]:
import numpy as np

### create one dimensional arrays using NumPy

In [111]:
a=np.array([5,6,9])

### access one dimensional arrays

In [112]:
a[0]

5

In [113]:
a[1]

6

### create two dimensional arrays using NumPy

In [114]:
a=np.array([[1,2],[3,4],[5,6]])

In [115]:
#way to check dimension in array -> "ndim"
a.ndim

2

In [116]:
a=np.array([5,6,9])

In [117]:
a.ndim

1

In [118]:
a=np.array([[1,2],[3,4],[5,6]])

In [119]:
# "itemsize" -> print byte size of each properties in an array
a.itemsize

8

In [120]:
a=np.array([5,6,9])

In [121]:
a.itemsize

8

In [122]:
a.dtype

dtype('int64')

In [123]:
a=np.array([[1,2],[3,4],[5,6]], dtype=np.float64)

In [124]:
a.itemsize

8

In [125]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [126]:
# "size" -> prints total number of elements
a.size

6

In [127]:
# "shape" -> prints information about dimension. like rows and columns.
a.shape

(3, 2)

In [128]:
# create an array with complex numbers
a=np.array([[1,2],[3,4],[5,6]], dtype=complex )

In [129]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

### create an array with zeros or ones.

In [130]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [131]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [132]:
# range() function create a list.
i = range(5)

In [133]:
i

range(0, 5)

In [134]:
i[0]

0

In [135]:
i[2]

2

In [136]:
# arange meaning -> array range
np.arange(1,5)

array([1, 2, 3, 4])

In [137]:
np.arange(1,5,2)

array([1, 3])

In [138]:
# "linspace function" linspace(start_number,stop_number,how many numbers between these two numbers)
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [139]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [140]:
a=np.array([[1,2],[3,4],[5,6]])

In [141]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [142]:
a.shape

(3, 2)

In [143]:
# "reshape" -> change columns and rows
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [144]:
a.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [145]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [146]:
# "ravel" -> flatten the array, that's mean make one dimension array. this is not change original array
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [147]:
a         

array([[1, 2],
       [3, 4],
       [5, 6]])

In [148]:
a.min()

1

In [149]:
a.max()

6

In [150]:
a.sum()

21

In [151]:
# "axis" -> axis =0, represents columns.
a.sum(axis=0)

array([ 9, 12])

In [152]:
# "axis" -> axis =1, represents rows.
a.sum(axis=1)

array([ 3,  7, 11])

In [153]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [154]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [155]:
# np.std() -> gives standard deviation
np.std(a)

1.707825127659933

In [165]:
a=np.array( [[1,2],[3,4]])

In [166]:
b=np.array([[5,6],[7,8]])

In [167]:
a

array([[1, 2],
       [3, 4]])

In [168]:
b

array([[5, 6],
       [7, 8]])

In [169]:
a+b

array([[ 6,  8],
       [10, 12]])

In [170]:
a*b

array([[ 5, 12],
       [21, 32]])

In [171]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [173]:
# "dot" gives matrix multiplication
# matrix_1.dot(matrix_2)
a.dot(b)

array([[19, 22],
       [43, 50]])