<a href="https://colab.research.google.com/github/TABEYWICKRAMA/BigData/blob/main/NumPy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([5,6,9])

In [3]:
a[0]

5

In [4]:
a[1]

6

In [6]:
a=np.array([[1,2],[3,4],[5,6]])

In [7]:
a.ndim

2

In [9]:
a=np.array([5,6,9])

In [10]:
a.ndim

1

In [36]:
a=np.array([[1,2],[3,4],[5,6]])

In [13]:
a.itemsize

8

In [14]:
a=np.array([5,6,9])

In [15]:
a.itemsize

8

In [16]:
a.dtype

dtype('int64')

In [17]:
a=np.array([[1,2],[3,4],[5,6]], dtype=np.float64)

In [18]:
a.itemsize

8

In [19]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [20]:
a.size

6

In [21]:
a.shape

(3, 2)

In [22]:
a=np.array([[1,2],[3,4],[5,6]], dtype=complex )

In [23]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
i = range(5)

In [27]:
i

range(0, 5)

In [28]:
i[0]

0

In [29]:
i[2]

2

In [30]:
np.arange(1,5)

array([1, 2, 3, 4])

In [31]:
np.arange(1,5,2)

array([1, 3])

In [33]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [35]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [37]:
a=np.array([[1,2],[3,4],[5,6]])

In [38]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
a.shape

(3, 2)

In [40]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
a.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [42]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [43]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
a.min()

1

In [45]:
a.max()

6

In [46]:
a.sum()

21

In [47]:
a.sum(axis=0)

array([ 9, 12])

In [48]:
a.sum(axis=1)

array([ 3,  7, 11])

In [51]:
a.sqrt()

AttributeError: ignored

In [49]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [50]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
np.std(a)

1.707825127659933

In [55]:
a=np.array( [[1,1],
            [0,1]] )

In [57]:
a=np.array( [[1,2],[3,4]])

In [58]:
b=np.array([[5,6],[7,8]])

In [59]:
a

array([[1, 2],
       [3, 4]])

In [60]:
b

array([[5, 6],
       [7, 8]])

In [61]:
a+b

array([[ 6,  8],
       [10, 12]])

In [62]:
a*b

array([[ 5, 12],
       [21, 32]])

In [63]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [64]:
a.dot(b)

array([[19, 22],
       [43, 50]])