<a href="https://colab.research.google.com/github/TABEYWICKRAMA/BigData/blob/main/Slicing%2C_Indexing_with_Boolean_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
#normal python list
n = [6,7,8]

In [4]:
n[0:2]

[6, 7]

In [5]:
n[-1]

8

In [6]:
#numpy array
a = np.array([6,7,8])

In [7]:
a[0:2]

array([6, 7])

In [8]:
a[-1]

8

In [9]:
a = np.array([[6,7,8],[1,2,3],[9,3,2]])   #multi-dimensional array

In [10]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [11]:
a[1,2]       #a[row,column]

3

In [12]:
a[0:2,2]    #this going o row, 1 row and get 2 column of both rows

array([8, 3])

In [13]:
a[-1]       #last row represents in here

array([9, 3, 2])

In [14]:
a[-1,0:2]

array([9, 3])

In [15]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [16]:
a = np.array([[6,7,8],[1,2,3],[9,3,2]])

In [17]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [18]:
for row in a:
  print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [19]:
# To flatten the multi-dimension array into single dimension array
for cell in a.flat:
  print(cell)

6
7
8
1
2
3
9
3
2


In [20]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)

In [21]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [22]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [23]:
# "vstack" - a and b arrays are vertically stacked 
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [24]:
# "vstack" -> a and b arrays are horizontally stacked 
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

## **Slicing**

In [25]:
a=np.arange(30).reshape(2,15)

In [26]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [27]:
# "hsplit","vsplit" -> used to divide an array into three different equal sizes 
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

### This result is hard to visualize, so print different three arrays in one by one

In [28]:
result =np.hsplit(a,3) 

In [29]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [30]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [31]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [32]:
result = np.vsplit(a,2)

In [33]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [34]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

indexing with boolean arrays

In [35]:
a = np.arange(12).reshape(3,4)

In [36]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
b = a > 4

In [38]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [39]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [40]:
a[b]=-1

In [41]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])