## **Import NumPy Library**


*   NumPy most usable feature is n dimentional array object, similar to python lists.




So why we use NumPy,


1.   Less memory
2.   Fast
3.   Convinient






----------------------------------------------------------------------------------

In [176]:
import numpy as np

### create one dimensional arrays using NumPy

In [177]:
a=np.array([5,6,9])

### access one dimensional arrays

In [178]:
a[0]

5

In [179]:
a[1]

6

### create two dimensional arrays using NumPy

In [180]:
a=np.array([[1,2],[3,4],[5,6]])

In [181]:
#way to check dimension in array -> "ndim"
a.ndim

2

In [182]:
a=np.array([5,6,9])

In [183]:
a.ndim

1

In [184]:
a=np.array([[1,2],[3,4],[5,6]])

In [185]:
# "itemsize" -> print byte size of each properties in an array
a.itemsize

8

In [186]:
a=np.array([5,6,9])

In [187]:
a.itemsize

8

In [188]:
a.dtype

dtype('int64')

In [189]:
a=np.array([[1,2],[3,4],[5,6]], dtype=np.float64)

In [190]:
a.itemsize

8

In [191]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [192]:
# "size" -> prints total number of elements
a.size

6

In [193]:
# "shape" -> prints information about dimension. like rows and columns.
a.shape

(3, 2)

In [194]:
# create an array with complex numbers
a=np.array([[1,2],[3,4],[5,6]], dtype=complex )

In [195]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

### create an array with zeros or ones.

In [196]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [197]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [198]:
# range() function create a list.
i = range(5)

In [199]:
i

range(0, 5)

In [200]:
i[0]

0

In [201]:
i[2]

2

In [202]:
# arange meaning -> array range
np.arange(1,5)

array([1, 2, 3, 4])

In [203]:
np.arange(1,5,2)

array([1, 3])

In [204]:
# "linspace function" linspace(start_number,stop_number,how many numbers between these two numbers)
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [205]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [206]:
a=np.array([[1,2],[3,4],[5,6]])

In [207]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [208]:
a.shape

(3, 2)

In [209]:
# "reshape" -> change columns and rows
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [210]:
a.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [211]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [212]:
# "ravel" -> flatten the array, that's mean make one dimension array. this is not change original array
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [213]:
a         

array([[1, 2],
       [3, 4],
       [5, 6]])

In [214]:
a.min()

1

In [215]:
a.max()

6

In [216]:
a.sum()

21

In [217]:
# "axis" -> axis =0, represents columns.
a.sum(axis=0)

array([ 9, 12])

In [218]:
# "axis" -> axis =1, represents rows.
a.sum(axis=1)

array([ 3,  7, 11])

In [219]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [220]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [221]:
# np.std() -> gives standard deviation
np.std(a)

1.707825127659933

In [222]:
a=np.array( [[1,2],[3,4]])

In [223]:
b=np.array([[5,6],[7,8]])

In [224]:
a

array([[1, 2],
       [3, 4]])

In [225]:
b

array([[5, 6],
       [7, 8]])

In [226]:
a+b

array([[ 6,  8],
       [10, 12]])

In [227]:
a*b

array([[ 5, 12],
       [21, 32]])

In [228]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [229]:
# "dot" gives matrix multiplication
# matrix_1.dot(matrix_2)
a.dot(b)

array([[19, 22],
       [43, 50]])